### ISSUE TITLE
mysql 只支持 8 ? 

### ISSUE THREAD

**Issue by djunny** [YaoApp/yao#1]
试了下 crm demo ，似乎用了 json_table 的一些方法，

没法用 sqlite3 引擎，好像也无法兼容 mariadb ？

看能否兼容一下，如果数据库要指定新版本，使用门槛一下上升了不少~

```
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(`industries`, '$[*]' columns (`F1` VARCHAR(255) path '$') ) AS `__JSON_T1` g...' at line 1
/Users/runner/work/yao/xun/utils/utils.go:22 (0x4a42364)
/Users/runner/work/yao/xun/dbal/query/query.go:53 (0x4a42340)
/Users/runner/work/yao/gou/query/gou/query.go:267 (0x4d4bd68)
/Users/runner/work/yao/gou/query/gou/query.go:162 (0x4d4b137)
/Users/runner/work/yao/gou/flow.process.go:91 (0x4b19cce)
/Users/runner/work/yao/gou/flow.process.go:77 (0x4b19be7)
```

换到 mariadb 10.6 + 后(支持 json_table)， 但提示：

```
{"message":"Table:service; 尚未加载","code":400,"context":null}
/Users/runner/work/yao/kun/exception/exception.go:111 (0x4d5ee29)
/Users/runner/work/yao/yao/table/table.go:93 (0x4d5edf3)
/Users/runner/work/yao/yao/table/process.go:35 (0x4d5a536)
/Users/runner/work/yao/gou/process.go:19 (0x4b111cf)
/Users/runner/work/yao/gou/api.http.go:94 (0x4b111c6)
```

**Comment by MatrixAge** [comment]
因为涉及一些json处理，我们尝试过兼容低版本的，但会带来一些问题，最后只能要求使用mysql8+，我相信对于使用者来说这不会是大问题（不涉及到项目数据迁移的情况下），我们也不建议您在没有深入了解Yao的情况下，将旧有项目数据迁移到Yao上。

Because it involves some json processing, we have tried to be compatible with lower versions, but it will bring some problems. In the end, we can only ask to use mysql8+. I believe this will not be a big problem for users (it does not involve project data migration). below), we also do not recommend that you migrate old project data to Yao without a deep understanding of Yao.

**Comment by trheyi** [comment]
DEMO CRM 的应用，使用到 QueryDSL 做统计查询，json_table 只用于  QueryDSL，数据表格，数据模型等支持 SQLite3, MySQL 5.7，MySQL 8.0。

QueryDSL 中带有 JSON字段查询的部分，目前仅兼容 MySQL 8.0，其他数据库暂未加入单元测试。后续有计划兼容 SQLite3, PostgreSQL 14, 以及 Mariadb 的高版本。

The application of DEMO CRM uses QueryDSL for statistical query, json_table is only used for QueryDSL, Tables, Models, etc. support SQLite3, MySQL 5.7, MySQL 8.0.

with JSON field in QueryDSL is currently only compatible with MySQL 8.0, and other databases have not yet been added to unit testing. There are plans to be compatible with SQLite3, PostgreSQL 14, and later versions of MariaDB.

**Comment by djunny** [comment]
了解，crm demo 初始化少给了一个命令：

```
yao run flows.init.menu
```

新手 migrate 后，进后台是空的，会有点蒙...
